"""Athena — plugin and skill distribution for the HomericIntelligence ecosystem.

Public surface is intentionally tiny. Most of Athena's value is the
host-side metadata (``.claude-plugin/``, ``.codex-plugin/``, ``skills/``),
not Python code. The single shipped script is
:func:`athena.validate_marketplace.main`, which exists to enforce that
``.claude-plugin/marketplace.json`` references real ``skills/<name>/`` folders.
"""

from __future__ import annotations

__all__ = ["__version__", "main"]


def __getattr__(name: str) -> str:
    """Lazy attribute lookup so ``__version__`` does not import-time fail.

    ``athena/_version.py`` is generated by ``hatch-vcs`` and is *not*
    present in the source distribution; we read it on first access.

    If the version file is missing or malformed we surface the failure to
    the developer (stderr) and raise — silent fallback to "0.0.0+unknown"
    masks real parse errors during dev, which is exactly the failure mode
    brushed aside at install-time that surfaces as a confusing "why does
    my build report an unrelated version" later.
    """
    if name == "__version__":
        import sys
        from pathlib import Path

        version_path = Path(__file__).parent / "_version.py"
        if not version_path.exists():
            print(
                f"athena: _version.py not present at {version_path}; "
                "the package was likely installed without hatch-vcs running.",
                file=sys.stderr,
            )
            raise RuntimeError("athena: __version__ unavailable — _version.py missing")
        # hatch-vcs writes: __version__ = "x.y.z"
        for line in version_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("__version__"):
                _, _, value = line.partition("=")
                cleaned = value.strip().strip('"').strip("'")
                if not cleaned:
                    raise RuntimeError(
                        f"athena: malformed _version.py at {version_path} — "
                        f"empty `__version__` value"
                    )
                return cleaned
        raise RuntimeError(
            f"athena: malformed _version.py at {version_path} — "
            "no `__version__` assignment found"
        )
    if name == "main":
        from athena.validate_marketplace import main

        return main
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)
